#!/usr/bin/env fish

set archASCII '
         \e[0;34m.
        \e[0;34m/ \
       \e[0;34m/   \    \e[1;37m         #     \e[1;34m| *
      \e[0;34m/^.   \   \e[1;37m#%" a#"e 6##%  \e[1;34m| | |-^-. |   | \ /
     \e[0;34m/  .-.  \  \e[1;37m#   #    #  #  \e[1;34m| | |   | |   |  X
    \e[0;34m/  (   ) _\ \e[1;37m#   %#e" #  #  \e[1;34m| | |   | ^._.| / \
   \e[1;34m/ _.~   ~._^\
  \e[1;34m/.^         ^.\ \e[0;37mTM\e[m'

echo -e "$archASCII"

# Generated with https://patorjk.com/software/taag/#p=display&f=Big&t=4b%20Fish%20config
printf "\033[33m
  _  _   _       ______ _     _                        __ _
 | || | | |     |  ____(_)   | |                      / _(_)
 | || |_| |__   | |__   _ ___| |__     ___ ___  _ __ | |_ _  __ _ 
 |__   _| '_ \  |  __| | / __| '_ \   / __/ _ \| '_ \|  _| |/ _\` |
    | | | |_) | | |    | \__ \ | | | | (_| (_) | | | | | | | (_| |
    |_| |_.__/  |_|    |_|___/_| |_|  \___\___/|_| |_|_| |_|\__, |
                                                             __/ |     
                                                            |___/         
\033[0m\n"

printf "\033[1;32mInstalling Fish...\033[0m\n"
paru -S fish --noconfirm

printf "\033[1;32mInstalling Fish plugin manager (Fisher)...\033[0m\n"
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

# Theme
printf "\033[1;32mInstalling Fish color theme (Rosé Pine)...\033[0m\n"
fisher install rose-pine/fish
fish_config theme save "Rosé Pine"

# fzf
if type -q fzf 
  printf "\033[1;32mInstalling Fish fzf plugin...\033[0m\n"
  fisher install PatrickF1/fzf.fish
end

#eza
if type -q eza
  printf "\033[1;32mInstalling Fish eza completions...\033[0m\n"
  mkdir -p $HOME/.config/fish/completions
  curl -L "https://raw.githubusercontent.com/eza-community/eza/refs/heads/main/completions/fish/eza.fish" -o $HOME/.config/fish/completions/eza.fish
end

#######################################
# Rebuild $HOME/.config/fish/config.fish
#######################################
printf "\033[1;32mRebuilding config.fish...\033[0m\n"
set fish_config_path "$HOME/.config/fish/config.fish"
# set fish_config_path "$HOME/Projects/arch-config/scripts/test_fish_config"
mkdir -p $HOME/.config/fish/
rm $fish_config_path

#######################################
# file header
set intro "\
# DO NOT EDIT THIS FILE : this content is regenerated automatically by a config script
if status is-interactive
"
printf "%s" $intro >> $fish_config_path

#######################################
# PATH section
printf "\n%s\n" "  #########################################" >> $fish_config_path
printf "%s\n" "  # Path-like variables" >> $fish_config_path
printf "%s\n" "  #########################################" >> $fish_config_path

printf "\n%s\n" "  # \$PATH" >> $fish_config_path
# Poetry
if type -q poetry 
  printf "%s\n" "  fish_add_path $HOME/.local/bin #PyPoetry" >> $fish_config_path
end
# Pyenv
if type -q pyenv
  printf "%s\n" "  fish_add_path $HOME/.pyenv #PyEnv" >> $fish_config_path
end
# CUDA
if test -d /opt/cuda/bin
  printf "%s\n" "  fish_add_path /opt/cuda/bin #CUDA" >> $fish_config_path
end

printf "\n%s\n" "  # Other general path-like variables" >> $fish_config_path
# CUDA
if test -d /opt/cuda/bin
  printf "%s\n" "  set -gx --path LD_LIBRARY_PATH $LD_LIBRARY_PATH /opt/cuda/lib64" >> $fish_config_path
end

#######################################
# Environment variable section
printf "\n%s\n" "  #########################################" >> $fish_config_path
printf "%s\n" "  # Environment variables" >> $fish_config_path
printf "%s\n" "  #########################################" >> $fish_config_path
printf "%s\n" "  set -gx LANG en_US.UTF-8" >> $fish_config_path

# Neovim
if type -q poetry 
  printf "%s\n" "  set -gx EDITOR nvim" >> $fish_config_path
end

# Java
if type -q java 
  printf "%s\n" "  # Java" >> $fish_config_path
  printf "%s\n" "  set -gx JDK_HOME /usr/lib/jvm/default/" >> $fish_config_path
  printf "%s\n" "  set -gx JAVA_HOME /usr/lib/jvm/default/" >> $fish_config_path
end

#######################################
# Aliases section 
printf "\n%s\n" "  #########################################" >> $fish_config_path
printf "%s\n" "  # Aliases" >> $fish_config_path
printf "%s\n" "  #########################################" >> $fish_config_path

# eza
if type -q eza 
  printf "%s\n" "  # eza" >> $fish_config_path
  printf "%s\n" '  alias eza="eza --time-style=long-iso"' >> $fish_config_path
  printf "%s\n" '  alias ls="eza"' >> $fish_config_path
  printf "%s\n" '  alias la="ls --long --all --header --icons"' >> $fish_config_path
  printf "%s\n" '  alias lg="ls --long --all --header --icons --git"' >> $fish_config_path
  printf "%s\n" '  alias less="less -R"' >> $fish_config_path
end

# fd
if type -q fd
  printf "%s\n" "  # fd" >> $fish_config_path
  printf "%s\n" '  alias fd="fd -HI"' >> $fish_config_path
end

#######################################
# Aliases section 
printf "\n%s\n" "  #########################################" >> $fish_config_path
printf "%s\n" "  # Tool specific configuration" >> $fish_config_path
printf "%s\n" "  #########################################" >> $fish_config_path

# fzf
printf "%s\n" "  # fzf" >> $fish_config_path
set fzf_config "\
  set -Ux FZF_DEFAULT_OPTS \"\\
  --height 20% --border \\
  --preview 'bat --style=numbers --color=always --line-range :500 {}'\"sour
"
printf "%s\n" $fzf_config >> $fish_config_path

# gpg-agent
printf "%s\n" "  # gpg-agent" >> $fish_config_path
printf "%s\n" "  set -x GPG_TTY (tty)" >> $fish_config_path
printf "%s\n" "  set -x SSH_AUTH_SOCK (gpgconf --list-dirs agent-ssh-socket)" >> $fish_config_path
printf "%s\n" "  gpgconf --launch gpg-agent" >> $fish_config_path

# pyenv
if type -q pyenv
  printf "\n%s\n" "  # pyenv" >> $fish_config_path
  printf "%s\n" "  set -Ux PYENV_ROOT $HOME/.pyenv" >> $fish_config_path
  printf "%s\n" "  pyenv init - | source" >> $fish_config_path
end

#######################################
# file footer
printf "\n%s\n" "end" >> $fish_config_path

#Set Fish as the default shell
printf "\033[1;32mSetting fish as the default shell...\033[0m\n"
chsh -s /bin/fish
